# ❌📈Analysis of data containing recording anomalies, hardware communication failures and systemic errors
- During data exploration with excel and sql, i discovered data with the following characteristics:
    - Ride_length > 1 day long (< 1440 minutes)
    - Ride_length < 1 minute long (> 1)
    - End_station_name or end_station_id empty
    - Data with negative ride lengths ( < 0)

**I performed the following audit and analysis in order to get a better understanding of the data**


In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Connect to database
engine = create_engine('postgresql://postgres:1998@localhost:5432/bike_ride_data')

# Only pull the relevant data for analysis
query = "SELECT* FROM trips_2025 WHERE ride_length < 1 OR ride_length >= 1440"
df_error_ride_data = pd.read_sql(query,engine)

print("Data loaded successfully")

Data loaded successfully


In [4]:
print(df_error_ride_data.head(50))

             ride_id  rideable_type          started_at            ended_at  \
0   14CD6059DA03A8F4  electric_bike 2025-01-27 10:42:00 2025-01-27 10:42:00   
1   EA38BB3B7F34BEE4  electric_bike 2025-01-05 16:39:00 2025-01-05 16:40:00   
2   616584F4B6C0AFEF  electric_bike 2025-01-05 16:38:00 2025-01-05 16:38:00   
3   D2A2934379C6D6AB  electric_bike 2025-01-15 20:06:00 2025-01-15 20:07:00   
4   6E354AB392871891  electric_bike 2025-01-28 07:46:00 2025-01-28 07:46:00   
5   B8852E3AC6024F1F  electric_bike 2025-01-08 19:52:00 2025-01-08 19:53:00   
6   589D79DDCF99C246  electric_bike 2025-01-24 17:49:00 2025-01-24 17:49:00   
7   A47E708A90721523  electric_bike 2025-01-16 11:30:00 2025-01-16 11:31:00   
8   F583B566CEEB610A  electric_bike 2025-01-16 14:47:00 2025-01-16 14:47:00   
9   DFC055174EA1F415  electric_bike 2025-01-25 18:37:00 2025-01-25 18:38:00   
10  EBBC4573D138A2AB  electric_bike 2025-01-28 15:13:00 2025-01-28 15:14:00   
11  3A33B9AF2416B0E7  electric_bike 2025-01-17 18:26

## 👨‍💻👨‍💻 Code breakdown 
*Here i used sqlalchemy's create engine to only pull data that was relevant to the characteristics above and loaded it to python's pandas dataframe for analysis*

*I ran the dataframe.head() to get a brief layout of the data*


In [ ]:
# Information about the bikes ride data that is erroneous 

df_error_ride_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152709 entries, 0 to 152708
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype         
---  ------              --------------   -----         
 0   ride_id             152709 non-null  object        
 1   rideable_type       152709 non-null  object        
 2   started_at          152709 non-null  datetime64[ns]
 3   ended_at            152709 non-null  datetime64[ns]
 4   ride_length         152709 non-null  float64       
 5   day_of_week         152709 non-null  int64         
 6   weekday             152709 non-null  object        
 7   start_station_name  63514 non-null   object        
 8   start_station_id    63514 non-null   object        
 9   end_station_name    35895 non-null   object        
 10  end_station_id      35895 non-null   object        
 11  start_lat           152709 non-null  float64       
 12  start_lng           152709 non-null  float64       
 13  end_lat             147333 no

## 👨‍💻👨‍💻 Code breakdown
*The data contains 152,709 entries or rows that either took more than one day to complete the ride or took less than a minute and all the columns were laoded in their correct data formats*

In [6]:
# Basic statistics of the data (searching to see which is relevant)
df_error_ride_data.describe()

,started_at,ended_at,ride_length,day_of_week,start_lat,start_lng,end_lat,end_lng
count,152709,152709,152709.000000,152709.000000,152709.000000,152709.000000,147333.000000,147333.000000
mean,2025-07-25 18:09:39.897844736,2025-07-25 19:04:51.194231808,55.188385,3.208337,41.902645,-87.646323,41.903164,-87.646423
min,2025-01-01 00:18:00,2025-01-01 00:18:00,-54.790000,0.000000,41.648501,-87.880000,41.650000,-87.880000
25%,2025-06-09 08:28:00,2025-06-09 09:58:00,0.190000,1.000000,41.880000,-87.660000,41.880000,-87.660000
50%,2025-07-28 16:54:00,2025-07-28 17:17:00,0.340000,3.000000,41.900000,-87.640000,41.900000,-87.640000
75%,2025-09-20 11:30:00,2025-09-20 11:54:00,0.570000,5.000000,41.930000,-87.630000,41.930000,-87.630000
max,2025-12-31 23:42:00,2025-12-31 23:43:00,1574.900000,6.000000,42.070000,-87.528232,42.070000,-87.528232
std,NaN,NaN,281.369734,2.088901,0.047673,0.030311,0.047182,0.030142


# 📆📆 1.0 First  Will first of all look into the ride data that took longer than one day 
   - ## 1.1 I will analysis the percentage of casual and annual members present in this data
   - ## 1.2 I will also investigate how many of these rides are classic bikes or electric bikes

In [ ]:
# filter for only the data with rides longer than 1 day 
system_error_mask = df_error_ride_data['ride_length'] >= 1440
long_day_rides = df_error_ride_data[system_error_mask]
len(long_day_rides['ride_id'].index)

# out of the 152709 entries, 5585 of those are bike rides where ride time exceeded 24 hours 
# meaning the bike wasn't docked by the rider 

5585

## 👨‍💻👨‍💻 Code breakdown
*I filtered the data so that i only worked with data that had ride length greater than one day or > 1440*

## ℹ️📑 Key Insight
- *The analysis shows that out of the 152,709 rides, 5,585 of those were bike rides that exceeded 24 hours and also did not have end station data (name or id)*

## 👨‍💼👨‍💼 Takeaway
- *These 5,585 rides were rides that likely had the following causes :* 
    - *riders might have had difficulty locking or docking the bikes*
    - *riders might have not left the bikes at the docking station and rather left the bikes elsewhere thus not registering any end station data*
- *As a result all these rides ended up probably timed out by the system after exceeding the 24 hour mark*

In [ ]:
#How many of these rides are members?
members_long_day_rides = long_day_rides['member_casual'] == 'member' # mask for members


members_riders = len(long_day_rides[members_long_day_rides].index ) # count how many of the rides > 1 day and are members there are 

total_errors = len(long_day_rides['ride_id'].index) # count all the >1 ride system errors

percentage_of_members = (members_riders / total_errors)* 100 # calculate the percentage of the members 


members_riders

# Out of the 5585 rides that were > 24 hrs , 908 of those belonged to the annual members. 




908

## 👨‍💻👨‍💻 Code breakdown
*At this stage, i wanted to dig deeper and find out how many rides, out of the 5,585, were ridden by Cyclistic annual members*

## ℹ️📑 Key Insight
*Results show that $908$ rides from the $ 5,585 $ rides actually belonged to annual members of the company*

## 👨‍💼👨‍💼 Takeaway
- **


In [83]:
# percentage of annual member riders 

percentage_of_members

# 16.26 % of the rides are member riders



16.257833482542523

In [84]:
# How many of the rides are casual riders?
casual_riders = total_errors - members_riders #calculate casual riders
casual_percentage = (casual_riders / total_errors) * 100 #calculate percentage

casual_riders

# 4677 of the rides are casual riders


4677

In [85]:
# percentage of casual riders 
casual_percentage

# 83.7 % are casual riders meaning there is a somehow a correlation between the casual riders and the docking system problem obeserved in the data

83.74216651745748

In [86]:
# Do these > 24 hrs system timeout errors happen to a particular bike type?




electric_bikes = long_day_rides['rideable_type'] == 'electric_bike'
classic_bikes = long_day_rides['rideable_type'] == 'classic_bike'
len(long_day_rides[classic_bikes].index)




# Out of the 5585 rides , all of them were classic bikes


5585

In [87]:
len(long_day_rides[electric_bikes].index)

# None of the rides that take more than 24 hours were electric bikes

0

## Now I am going to look at the other erroneous data , where I found rides less than one minute and also had empty end station data
### I will investigate whether those rides are tied to a perticular bike type 
### I will also investigate how many of these rides belonged to annual members and casual riders

In [ ]:
len(df_error_ride_data.index) 

# Will separate the data to only look at data where ride_length < 1 min

too_short_rides = (df_error_ride_data['ride_length'] < 1) | (df_error_ride_data['end_station_name'] == '')
len(df_error_ride_data[too_short_rides].index)

# 147,124 rides were less than one minute long


147124

In [ ]:
df_short_rides = df_error_ride_data[too_short_rides]
df_short_rides.sort_values(by= 'ride_length', ascending= False) 

# How many of these rides are electric bike rides?
e_bikes_mask = df_short_rides['rideable_type'] == 'electric_bike'
len(df_short_rides[e_bikes_mask].index)



# Out of the 147,124 rides that were less than one minute long , 147,112 were electric bikes

147112

In [59]:
# Percentage of the electric bikes

e_bikes_percentage =(len(df_short_rides[e_bikes_mask].index) / len(df_short_rides.index)) * 100
e_bikes_percentage


# About 99,99% of the rides were electric bikes

99.99184361490987

## I isolated just how many of the rides that were less than one minute long, were a Daylight Savings Time recording error (< 0)

In [ ]:
# Calculating how many rides were a result of the DST
daylight_saving_time_ride_mask = df_short_rides['ride_length'] < 0 
len(df_short_rides[daylight_saving_time_ride_mask].index)

# 29 rides that were less than one minute long are attributed to the DST recording error 

29

In [65]:
# How many of the < 1 and also  rides were classic bikes
classic_bikes_mask = df_short_rides['rideable_type'] == 'classic_bike'
len(df_short_rides[classic_bikes_mask].index)

#Upon further investigation, i have found that these bike rides that were in the negatives for classic bikes were due to Daylight Saving Time and thus won't be considered as relevant to the 
# less than one minute ride error analysis


12

In [ ]:
# And of the 12 rides, how many are a result of DST
classic_bikes_mask = (df_short_rides['rideable_type'] == 'classic_bike') & (df_short_rides['ride_length'] < 0)
len(df_short_rides[classic_bikes_mask].index)

# Therefore all of the 12 rides for classic bikes in the second error, only ocurred as a result of DST and shall be excluded 


12

In [ ]:
# 29 - 12 = 17 
# 17 rides were electric bike rides that were affected by DST and will be excluded as well

# Going back to rides that were < 1 minute long but > than 0 (The non-DST related errors)

In [ ]:
df_e_bike_short_rides = df_short_rides[e_bikes_mask]
len(df_e_bike_short_rides)

# How many of these electric bike errors were caused by annual members?
short_rides_member_mask = df_e_bike_short_rides['member_casual'] == 'member'

len(df_e_bike_short_rides[short_rides_member_mask].index)

# There were 68,213 rides attributed to annual members that exeperienced the less than minute ride 

68213

In [75]:
# member percentage 
member_short_rides_perc = (len(df_e_bike_short_rides[short_rides_member_mask].index) / len(df_e_bike_short_rides.index)) * 100
round(member_short_rides_perc,2)

46.37

In [71]:
# How many were casual riders?
short_rides_casual_mask  = df_e_bike_short_rides['member_casual'] == 'casual'
len(df_e_bike_short_rides[short_rides_casual_mask].index)

78899

In [77]:
# casual percentage
casual_short_rides_perc = 100 - 46.37
casual_short_rides_perc

53.63